title: Emily Nguyen
email: emilymylinh@gmail.com
description: Jekyll boilerplate
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000/" # the base hostname & protocol for your site, e.g. http://example.com
github_username: emnguyen

# Build settings
markdown: kramdown
plugins:
  - jekyll-autoprefixer
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
